# Site settings
title: "Deepak Saini"
email: sainideepak119@gmail.com
description: "Deepak Saini's personal site."
baseurl: ""
# url: ""
title_description: "Hi there! I am Deepak Saini. I am a Research Engineer at Microsoft Research where I work on large scale recommendation problems. My work has an intersection between machine learning and efficient system design. I work on developing and deploying Extreme Classification (XC) algorithms with guidance from <a href='http://manikvarma.org/'>Manik Varma</a>. Algorithms developed by me are deployed on Bing, MSN and other Microsoft products where they are helping hundreds of millions of users and (in-process) generating millions of dollars in revenue by showing more relevant and presonalized recommendations. <br> Before joining MSR, I worked as AI Engineer at Zomato to determine the best personalized ordering of restaurants for users on the App home page. Previously, I had obtained a Bachelor's and Master's degree in Computer Science and Engineering from <a href='https://www.cse.iitd.ac.in/'>IIT Delhi</a> in 2018"
title_image: "https://i.postimg.cc/904rSbRr/Personal-Website-Photo.jpg"
# google_analytics: ""
# disqus_account: 
# github_repository: 
# addthis_id: 
post_limit: 5

# Social usernames/URLs
# twitter_username: 
github_username:  DeepakSaini119
# instagram_username: 
# reddit_username: 
linkedin_link: https://www.linkedin.com/in/deepak-saini-502732108/
# google_plus_link: 
stackoverflow_link: https://stackoverflow.com/users/3924566/deepak-saini
# xing_link:
# facebook_link:

# Footer
footer_right: "Theme from <a href=\"https://github.com/jacobtomlinson/carte-noire\">carte-noire on Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
